OnlinePrintingService/Models/AppUser.cs
using Microsoft.AspNet.Identity.EntityFramework;

namespace OnlinePrintingService.Models
{
    public class AppUser
    {

        public string Email { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string PhoneNumber { get; set; }

        public string Password { get; set; }

        public string ConfirmPassword { get; set; }
    }
}

OnlinePrintingService/Controllers/Common/AppUserController.cs
using Microsoft.AspNet.Identity;
using System.Web.Helpers;
using System.Web.Mvc;
using Microsoft.Owin.Security;
using System.Web;
using OnlinePrintingService.ViewModel;
using System.Diagnostics;
using System.Linq;
using OnlinePrintingService.Helper;
using OnlinePrintingService.Models;
 using System.Net.Http;
using System;
using System.Collections.Generic;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Net;
using Newtonsoft.Json;

namespace OnlinePrintingService.Controllers
{
    public class AppUserController : Controller
    {
        public class UserAuth
        {
            public string access_token { get; set; }
            public string token_type { get; set; }

            public string expires_in { get; set; }

            public string userName { get; set; }

            public string issued { get; set; }
            public string expires { get; set; }

        }
        
        // GET: AppUser
        public ActionResult SignUp()
        {
            return View();
        }


        [HttpPost]
        public ActionResult SignUp(SignUpViewModel signUpViewModel)
        {
            if (ModelState.IsValid)
            {

                {
                    var passwordHash = Crypto.HashPassword(signUpViewModel.Password);
                    var user = new AppUser()

                    {
                        Email = signUpViewModel.Email,
                        FirstName = signUpViewModel.FirstName,
                        LastName = signUpViewModel.LastName,
                        PhoneNumber = signUpViewModel.PhoneNumber,
                        Password = signUpViewModel.Password,
                        ConfirmPassword = signUpViewModel.ConfirmPassword

                    };
                    HttpClient client = new HttpClient();
                    client.BaseAddress = new Uri("https://localhost:44398/api/Account/Register");

                    var intr = client.PostAsJsonAsync<AppUser>("Register", user);
                    intr.Wait();
                    var response = intr.Result;
                  
                    Debug.Print(response.ReasonPhrase);


                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                ModelState.AddModelError("SignUp Error", "Invalid data");
                return View();
            }
        }


        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Login(LoginViewModel loginViewModel)
        {
            var nvc = new List<KeyValuePair<string, string>>();
            nvc.Add(new KeyValuePair<string, string>("grant_type", "password"));
            nvc.Add(new KeyValuePair<string, string>("username", loginViewModel.UserName));
            nvc.Add(new KeyValuePair<string, string>("password", loginViewModel.Password));
            var client = new HttpClient();
            var req = new HttpRequestMessage(HttpMethod.Post, "https://localhost:44398/api/token") { Content = new FormUrlEncodedContent(nvc) };
            var res = await client.SendAsync(req);
            if (res.StatusCode == HttpStatusCode.OK)
            {
                
                string responseBody = await res.Content.ReadAsStringAsync();
                UserAuth usr = JsonConvert.DeserializeObject<UserAuth>(responseBody);

               
                if (usr.userName == "admin") {
                    Cookiez.AddCookie(usr.userName, "Admin", Response);
                    return RedirectToAction("Order", "AdminOrder");
                }
                Cookiez.AddCookie(usr.userName, "User", Response);
                return RedirectToAction("Index", "Home");
            }
            ModelState.AddModelError("SignUp Error", "Invalid data");
            return View();
        }

       
        public ActionResult Logout()
        {
            
            Cookiez.RemoveCookie(HttpContext.ApplicationInstance.Response);
            return RedirectToAction("Index", "Home");
        }

        
    }
}

OnlinePrintingService/Views/AppUser/Login.cshtml
@model OnlinePrintingService.ViewModel.LoginViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>Login to Adey </title>
    <link rel="stylesheet" href="~/StyleSheets/Signup.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="icon" type="image/png" href="../Images/favicon.png" />
</head>

<body>
    <div class="signup__container">
        <div class="container__child signup__thumbnail">
            <img ID="Image2" runat="server" src="~/Images/signin.jpg" />

        </div>

        <div class="signup-form container__child" style="width: 18rem;">
            <div class="card-body">

                <div>

                    <h1 style="margin-top:-30px; margin-bottom:30px; font-weight:bold">Sign In</h1>
                    <div>
                        @using (Html.BeginForm("Login", "AppUser", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-row textInput">
                                <div class="form-group">

                                    @Html.TextBoxFor(va => va.UserName, new { placeholder = "User Name", @class = "form-control" })
                                    @Html.ValidationMessageFor(va => va.UserName)

                                </div>
                            </div>



                            <div class="form-row textInput" style="margin-top:15px;">
                                <div class="form-group">

                                    @Html.TextBoxFor(va => va.Password, new { placeholder = "Password", @class = "form-control" })
                                    @Html.ValidationMessageFor(va => va.Password)

                                </div>
                            </div>

                            @Html.ValidationSummary()
                            <div style="display:flex; ">
                                <button type="submit" class="btn btn-success" style="background-color: #febe19;color:black; font-weight:500;border:none">Login</button>
                                <a href="../AppUser/SignUp" style="align-self:flex-end; margin-left:10px;text-decoration:none; color:darkgrey;">Create an account</a>
                            </div>

                        }

                    </div>


                </div>
            </div>
        </div>
    </div>


</body>

</html>

OnlinePrintingService/Views/AppUser/SignIn.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="utf-8" />
    <link href="Content/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" /><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body style="padding-top:20px">
    <div class="col-md-10 col-md-offset-1">
        <div class="well">
            <!--Table to capture username and password-->
            <table class="table table-bordered">
                <thead>
                    <tr class="success">
                        <th colspan="2">
                            Existing User Login
                            <a href="Register.html" class="btn btn-success pull-right">
                                Register
                            </a>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Usename</td>
                        <td>
                            <input type="text" id="txtUsername" placeholder="Username" />
                        </td>
                    </tr>
                    <tr>
                        <td>Password</td>
                        <td>
                            <input type="password" id="txtPassword"
                                   placeholder="Password" />
                        </td>
                    </tr>
                    <tr class="success">
                        <td colspan="2">
                            <input id="btnLogin" class="btn btn-success" type="button"
                                   value="Login" />
                        </td>
                    </tr>
                </tbody>
            </table>
            <!--Bootstrap alert to display error message if the login fails-->
            <div id="divError" class="alert alert-danger collapse">
                <a id="linkClose" href="#" class="close">&times;</a>
                <div id="divErrorText"></div>
            </div>
        </div>
    </div>

    <script src="Scripts/jquery-1.10.2.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {

            $('#linkClose').click(function () {
                $('#divError').hide('fade');
            });

            $('#btnLogin').click(function () {
                $.ajax({
                    // Post username, password & the grant type to /token
                    url: '/token',
                    method: 'POST',
                    contentType: 'application/json',
                    data: {
                        username: $('#txtUsername').val(),
                        password: $('#txtPassword').val(),
                        grant_type: 'password'
                    },
                    // When the request completes successfully, save the
                    // access token in the browser session storage and
                    // redirect the user to Data.html page. We do not have
                    // this page yet. So please add it to the
                    // EmployeeService project before running it
                    success: function (response) {
                        sessionStorage.setItem("accessToken", response.access_token);
                        window.location.href = "Data.html";
                    },
                    // Display errors if any in the Bootstrap alert <div>
                    error: function (jqXHR) {
                        $('#divErrorText').text(jqXHR.responseText);
                        $('#divError').show('fade');
                    }
                });
            });
        });
    </script>
</body>
</html>

OnlinePrintingService/Views/AppUser/SignUp.cshtml
@model OnlinePrintingService.ViewModel.SignUpViewModel
@{
    ViewBag.Title = "SignUp";
    Layout = null;
}

<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8">
    <title>Adey Printing | Signup</title>
    <link rel="stylesheet" href="../StyleSheets/Signup.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="icon" type="image/png" href="../Images/favicon.png" />
    <style>
        .textInput {
            margin-top: 15px;
        }
    </style>
</head>

<body>
    <div class="signup__container">
        <div class="container__child signup__thumbnail">
            <img ID="Image1" runat="server" src="../Images/signup.jpg" />

        </div>

        <div class="signup-form container__child" style=" width: 18rem;">
            <div class="card-body">

                <div>
                    <h1 style="margin-top:-30px; margin-bottom:30px; font-weight:bold">Sign Up</h1>
                    @using (Html.BeginForm("SignUp", "AppUser", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-row textInput">
                            <div class="form-group">

                                @Html.TextBoxFor(va => va.FirstName, new { placeholder = "First Name", @class = "form-control" })
                                @Html.ValidationMessageFor(va => va.FirstName)

                            </div>
                        </div>
                        <div class="form-row textInput">
                            <div class="form-group">

                                @Html.TextBoxFor(va => va.LastName, new { placeholder = "Last Name", @class = "form-control" })
                                @Html.ValidationMessageFor(va => va.LastName)

                            </div>
                        </div>


                        <div class="form-row textInput">
                            <div class="form-group">

                                @Html.TextBoxFor(va => va.Email, new { placeholder = "Email", @class = "form-control" })
                                @Html.ValidationMessageFor(va => va.Email)

                            </div>
                        </div>
                        <div class="form-row textInput">
                            <div class="form-group">

                                @Html.TextBoxFor(va => va.PhoneNumber, new { placeholder = "Phone Number", @class = "form-control" })
                                @Html.ValidationMessageFor(va => va.PhoneNumber)

                            </div>
                        </div>

                        <div class="form-row textInput">
                            <div class="form-group">

                                @Html.TextBoxFor(va => va.Password, new { placeholder = "Password", @class = "form-control" })
                                @Html.ValidationMessageFor(va => va.Password)

                            </div>
                        </div>
                        <div class="form-row textInput">
                            <div class="form-group">

                                @Html.TextBoxFor(va => va.ConfirmPassword, new { placeholder = "Confirm Password", @class = "form-control" })
                                @Html.ValidationMessageFor(va => va.ConfirmPassword)

                            </div>
                        </div>
                        @Html.ValidationSummary()
                        <div style="display:flex; ">
                            <button type="submit" class="btn btn-success" style="background-color: #212025;color:white; font-weight:500;border:none">Register</button>
                            <a href="../AppUser/Login" style="align-self:flex-end; margin-left:10px;text-decoration:none; color:darkgrey;">I have an account</a>
                        </div>

                    }

                </div>



            </div>
        </div>
    </div>


</body>

OnlinePrintingService/Views/AppUser/UserHome.cshtml
@{
    ViewBag.Title = "UserHome";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<html>

<head>

    <link rel="stylesheet" href="../StyleSheets/UserHome.css" type="text/css" />

    <title>Adey Printing</title>

</head>




<body>


    <div class="first-container">
        <div class=" first-container-left">
            <h1 class="headText">Print Your Ideas</h1>
            <p>
                Welcome to adey online printing service. <br /> High Quality Printing Service
            </p>
            <Button ID="orderNowB" class="button" Text="">Order Now</Button>
        </div>
        <div class="first-container-right">
            <img ID="Image1" src="~/Images/Home.png" />
        </div>
    </div>

    <!--services head -->
    <div class="container services">
        <h1 class="headText">Our Services</h1>
    </div>
    <p style="text-align:center;margin-top:-15px;">We provide high quality printing services for</p>

    <!--services -->
    <div class="first-container">
        <!--business card -->
        <a href="Pricing.aspx">

            <div class="card ">
                <img class="card-img-top" src="../Images/UserHome/businesscard.jpg" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Business Cards</h5>
                    <p class="card-text"></p>

                </div>
            </div>
        </a>


        <!--post Card -->
        <a href="Pricing.aspx">
            <div class="card ">
                <img class="card-img-top" src="../Images/UserHome/postcard.jpg" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Post Cards</h5>
                    <p class="card-text"></p>

                </div>
            </div>

        </a>

        <!--Brochures -->
        <a href="Pricing.aspx">
            <div class="card ">
                <img class="card-img-top" src="../Images/UserHome/brochure.jpg" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Brochures</h5>
                    <p class="card-text"></p>

                </div>
            </div>

        </a>

        <!--Stickers -->
        <a href="Pricing.aspx">
            <div class="card ">
                <img class="card-img-top" src="../Images/UserHome/sticker.jpg" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Stickers</h5>
                    <p class="card-text"></p>

                </div>
            </div>
        </a>

    </div>

    <!-- -->
    <!--quality head -->
    <!--Quality -->
    <div>
        <h1 class="headText services">We Believe in Quality</h1>
        <p style="text-align:center;margin-bottom:30px;">
            We don't compromise quality. We always deliver the
            quality you desire!
        </p>
        <div class="first-container gifcontainer">
            <div class="gifimage">
                <img src="../Images/UserHome/gifImage.jpg" alt="Card image cap">
            </div>
            <div class="gifthumb">
                <img src="../Images/UserHome/homegif.gif" alt="Card image cap">
            </div>
        </div>
    </div>


</body>
</html>